/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.vcs_demo_nov27;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * AllTypes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`all types`")
public class AllTypes implements Serializable {

    private Integer id;
    private String clobColumn;
    private Boolean booleanColumn;
    private String textColumn;
    private Integer integerColumn;
    private Short shortColumn;
    private Long longColumn;
    private BigDecimal doubleColumn;
    private Double floatColumn;
    private Long bigIntegerColumn;
    private BigDecimal bigDecimalColumn;
    private String stringColumn;
    private String characterColumn;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobColumn;
    private Date dateColumn;
    private Date dateDatetimeColumn;
    private Date dateTimestampColumn;
    private Time timeColumn;
    private Timestamp timestampColumn;
     
    private LocalDateTime datetimeColumn;
    private Short byteColumn;
     
    private LocalDateTime datetimeTimestampColumn;
    private Timestamp timestampDatetimeColumn;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "\"all types_id_seq\"" , schema = "public", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`Clob Column`", nullable = true, length = 2147483647)
    public String getClobColumn() {
        return this.clobColumn;
    }

    public void setClobColumn(String clobColumn) {
        this.clobColumn = clobColumn;
    }

    @Column(name = "`Boolean Column`", nullable = true)
    public Boolean getBooleanColumn() {
        return this.booleanColumn;
    }

    public void setBooleanColumn(Boolean booleanColumn) {
        this.booleanColumn = booleanColumn;
    }

    @Column(name = "`Text Column`", nullable = true, length = 2059)
    public String getTextColumn() {
        return this.textColumn;
    }

    public void setTextColumn(String textColumn) {
        this.textColumn = textColumn;
    }

    @Column(name = "`Integer Column`", nullable = true, scale = 0, precision = 10)
    public Integer getIntegerColumn() {
        return this.integerColumn;
    }

    public void setIntegerColumn(Integer integerColumn) {
        this.integerColumn = integerColumn;
    }

    @Column(name = "`Short Column`", nullable = true, scale = 0, precision = 5)
    public Short getShortColumn() {
        return this.shortColumn;
    }

    public void setShortColumn(Short shortColumn) {
        this.shortColumn = shortColumn;
    }

    @Column(name = "`Long Column`", nullable = true, scale = 0, precision = 19)
    public Long getLongColumn() {
        return this.longColumn;
    }

    public void setLongColumn(Long longColumn) {
        this.longColumn = longColumn;
    }

    @Column(name = "`Double Column`", nullable = true, scale = 8, precision = 16)
    public BigDecimal getDoubleColumn() {
        return this.doubleColumn;
    }

    public void setDoubleColumn(BigDecimal doubleColumn) {
        this.doubleColumn = doubleColumn;
    }

    @Column(name = "`Float Column`", nullable = true, scale = 5, precision = 10)
    public Double getFloatColumn() {
        return this.floatColumn;
    }

    public void setFloatColumn(Double floatColumn) {
        this.floatColumn = floatColumn;
    }

    @Column(name = "`BigInteger Column`", nullable = true, scale = 0, precision = 19)
    public Long getBigIntegerColumn() {
        return this.bigIntegerColumn;
    }

    public void setBigIntegerColumn(Long bigIntegerColumn) {
        this.bigIntegerColumn = bigIntegerColumn;
    }

    @Column(name = "`BigDecimal Column`", nullable = true, scale = 17, precision = 34)
    public BigDecimal getBigDecimalColumn() {
        return this.bigDecimalColumn;
    }

    public void setBigDecimalColumn(BigDecimal bigDecimalColumn) {
        this.bigDecimalColumn = bigDecimalColumn;
    }

    @Column(name = "`String Column`", nullable = true, length = 20)
    public String getStringColumn() {
        return this.stringColumn;
    }

    public void setStringColumn(String stringColumn) {
        this.stringColumn = stringColumn;
    }

    @Column(name = "`Character Column`", nullable = true, length = 1)
    public String getCharacterColumn() {
        return this.characterColumn;
    }

    public void setCharacterColumn(String characterColumn) {
        this.characterColumn = characterColumn;
    }

    @Column(name = "`Blob Column`", nullable = true)
    public byte[] getBlobColumn() {
        return this.blobColumn;
    }

    public void setBlobColumn(byte[] blobColumn) {
        this.blobColumn = blobColumn;
    }

    @Column(name = "`Date Column`", nullable = true)
    public Date getDateColumn() {
        return this.dateColumn;
    }

    public void setDateColumn(Date dateColumn) {
        this.dateColumn = dateColumn;
    }

    @Column(name = "`Date_datetime Column`", nullable = true)
    public Date getDateDatetimeColumn() {
        return this.dateDatetimeColumn;
    }

    public void setDateDatetimeColumn(Date dateDatetimeColumn) {
        this.dateDatetimeColumn = dateDatetimeColumn;
    }

    @Column(name = "`Date_Timestamp Column`", nullable = true)
    public Date getDateTimestampColumn() {
        return this.dateTimestampColumn;
    }

    public void setDateTimestampColumn(Date dateTimestampColumn) {
        this.dateTimestampColumn = dateTimestampColumn;
    }

    @Column(name = "`Time Column`", nullable = true)
    public Time getTimeColumn() {
        return this.timeColumn;
    }

    public void setTimeColumn(Time timeColumn) {
        this.timeColumn = timeColumn;
    }

    @Column(name = "`Timestamp Column`", nullable = true)
    public Timestamp getTimestampColumn() {
        return this.timestampColumn;
    }

    public void setTimestampColumn(Timestamp timestampColumn) {
        this.timestampColumn = timestampColumn;
    }

    @Column(name = "`Datetime Column`", nullable = true)
    public LocalDateTime getDatetimeColumn() {
        return this.datetimeColumn;
    }

    public void setDatetimeColumn(LocalDateTime datetimeColumn) {
        this.datetimeColumn = datetimeColumn;
    }

    @Column(name = "`Byte Column`", nullable = true, scale = 0, precision = 5)
    public Short getByteColumn() {
        return this.byteColumn;
    }

    public void setByteColumn(Short byteColumn) {
        this.byteColumn = byteColumn;
    }

    @Column(name = "`Datetime_Timestamp Column`", nullable = true)
    public LocalDateTime getDatetimeTimestampColumn() {
        return this.datetimeTimestampColumn;
    }

    public void setDatetimeTimestampColumn(LocalDateTime datetimeTimestampColumn) {
        this.datetimeTimestampColumn = datetimeTimestampColumn;
    }

    @Column(name = "`Timestamp_Datetime Column`", nullable = true)
    public Timestamp getTimestampDatetimeColumn() {
        return this.timestampDatetimeColumn;
    }

    public void setTimestampDatetimeColumn(Timestamp timestampDatetimeColumn) {
        this.timestampDatetimeColumn = timestampDatetimeColumn;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AllTypes)) return false;
        final AllTypes allTypes = (AllTypes) o;
        return Objects.equals(getId(), allTypes.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

