/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.vcs_demo_nov27;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Alltypes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ALLTYPES`")
public class Alltypes implements Serializable {

    private Integer pkid;
    private Short smallintcol;
    private Integer integercol;
    private BigInteger bigintcol;
    private BigDecimal doublecol;
    private Long longcol;
    private Double floatcol;
    private BigDecimal bigdeccol;
    private String charcol;
    private String stringcol;
    private String clobcol;
    private String textcol;
    private Date datecol;
    private Time timecol;
    private Timestamp timestampcol;
    private Boolean booleancol;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobcol;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`PKID`", nullable = false, scale = 0, precision = 10)
    public Integer getPkid() {
        return this.pkid;
    }

    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    @Column(name = "`SMALLINTCOL`", nullable = true, scale = 0, precision = 5)
    public Short getSmallintcol() {
        return this.smallintcol;
    }

    public void setSmallintcol(Short smallintcol) {
        this.smallintcol = smallintcol;
    }

    @Column(name = "`INTEGERCOL`", nullable = true, scale = 0, precision = 10)
    public Integer getIntegercol() {
        return this.integercol;
    }

    public void setIntegercol(Integer integercol) {
        this.integercol = integercol;
    }

    @Column(name = "`BIGINTCOL`", nullable = true, scale = 0, precision = 20)
    public BigInteger getBigintcol() {
        return this.bigintcol;
    }

    public void setBigintcol(BigInteger bigintcol) {
        this.bigintcol = bigintcol;
    }

    @Column(name = "`DOUBLECOL`", nullable = true, scale = 9, precision = 16)
    public BigDecimal getDoublecol() {
        return this.doublecol;
    }

    public void setDoublecol(BigDecimal doublecol) {
        this.doublecol = doublecol;
    }

    @Column(name = "`LONGCOL`", nullable = true, scale = 0, precision = 18)
    public Long getLongcol() {
        return this.longcol;
    }

    public void setLongcol(Long longcol) {
        this.longcol = longcol;
    }

    @Column(name = "`FLOATCOL`", nullable = true, scale = 4, precision = 8)
    public Double getFloatcol() {
        return this.floatcol;
    }

    public void setFloatcol(Double floatcol) {
        this.floatcol = floatcol;
    }

    @Column(name = "`BIGDECCOL`", nullable = true, scale = 10, precision = 25)
    public BigDecimal getBigdeccol() {
        return this.bigdeccol;
    }

    public void setBigdeccol(BigDecimal bigdeccol) {
        this.bigdeccol = bigdeccol;
    }

    @Column(name = "`CHARCOL`", nullable = true, length = 1)
    public String getCharcol() {
        return this.charcol;
    }

    public void setCharcol(String charcol) {
        this.charcol = charcol;
    }

    @Column(name = "`STRINGCOL`", nullable = true, length = 255)
    public String getStringcol() {
        return this.stringcol;
    }

    public void setStringcol(String stringcol) {
        this.stringcol = stringcol;
    }

    @Column(name = "`CLOBCOL`", nullable = true, length = 1048576)
    public String getClobcol() {
        return this.clobcol;
    }

    public void setClobcol(String clobcol) {
        this.clobcol = clobcol;
    }

    @Column(name = "`TEXTCOL`", nullable = true, length = 2255)
    public String getTextcol() {
        return this.textcol;
    }

    public void setTextcol(String textcol) {
        this.textcol = textcol;
    }

    @Column(name = "`DATECOL`", nullable = true)
    public Date getDatecol() {
        return this.datecol;
    }

    public void setDatecol(Date datecol) {
        this.datecol = datecol;
    }

    @Column(name = "`TIMECOL`", nullable = true)
    public Time getTimecol() {
        return this.timecol;
    }

    public void setTimecol(Time timecol) {
        this.timecol = timecol;
    }

    @Column(name = "`TIMESTAMPCOL`", nullable = true)
    public Timestamp getTimestampcol() {
        return this.timestampcol;
    }

    public void setTimestampcol(Timestamp timestampcol) {
        this.timestampcol = timestampcol;
    }

    @Column(name = "`BOOLEANCOL`", nullable = true)
    public Boolean getBooleancol() {
        return this.booleancol;
    }

    public void setBooleancol(Boolean booleancol) {
        this.booleancol = booleancol;
    }

    @Column(name = "`BLOBCOL`", nullable = true)
    public byte[] getBlobcol() {
        return this.blobcol;
    }

    public void setBlobcol(byte[] blobcol) {
        this.blobcol = blobcol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Alltypes)) return false;
        final Alltypes alltypes = (Alltypes) o;
        return Objects.equals(getPkid(), alltypes.getPkid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPkid());
    }
}

