/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.vcs_demo_nov27;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Objects;

public class PolicyInfoBttId implements Serializable {

    private String policyId;
    private Integer coverage;
    private Date busStart;
    private Date busEnd;
    private Timestamp sysStart;
    private Timestamp sysEnd;
    private Timestamp tsId;

    public String getPolicyId() {
        return this.policyId;
    }

    public void setPolicyId(String policyId) {
        this.policyId = policyId;
    }

    public Integer getCoverage() {
        return this.coverage;
    }

    public void setCoverage(Integer coverage) {
        this.coverage = coverage;
    }

    public Date getBusStart() {
        return this.busStart;
    }

    public void setBusStart(Date busStart) {
        this.busStart = busStart;
    }

    public Date getBusEnd() {
        return this.busEnd;
    }

    public void setBusEnd(Date busEnd) {
        this.busEnd = busEnd;
    }

    public Timestamp getSysStart() {
        return this.sysStart;
    }

    public void setSysStart(Timestamp sysStart) {
        this.sysStart = sysStart;
    }

    public Timestamp getSysEnd() {
        return this.sysEnd;
    }

    public void setSysEnd(Timestamp sysEnd) {
        this.sysEnd = sysEnd;
    }

    public Timestamp getTsId() {
        return this.tsId;
    }

    public void setTsId(Timestamp tsId) {
        this.tsId = tsId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PolicyInfoBtt)) return false;
        final PolicyInfoBtt policyInfoBtt = (PolicyInfoBtt) o;
        return Objects.equals(getPolicyId(), policyInfoBtt.getPolicyId()) &&
                Objects.equals(getCoverage(), policyInfoBtt.getCoverage()) &&
                Objects.equals(getBusStart(), policyInfoBtt.getBusStart()) &&
                Objects.equals(getBusEnd(), policyInfoBtt.getBusEnd()) &&
                Objects.equals(getSysStart(), policyInfoBtt.getSysStart()) &&
                Objects.equals(getSysEnd(), policyInfoBtt.getSysEnd()) &&
                Objects.equals(getTsId(), policyInfoBtt.getTsId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPolicyId(),
                getCoverage(),
                getBusStart(),
                getBusEnd(),
                getSysStart(),
                getSysEnd(),
                getTsId());
    }
}
